# Generated by Django 4.2.7 on 2024-04-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('bmi', models.FloatField()),
                ('insulin', models.FloatField()),
                ('skinthickness', models.FloatField()),
                ('pregnancies', models.FloatField()),
                ('Age', models.FloatField()),
                ('DiabetesPedigree', models.FloatField()),
                ('Prediction', models.CharField(max_length=20)),
            ],
        ),
    ]
