# Generated by Django 4.2.7 on 2024-02-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diabetesinput',
            old_name='BMI',
            new_name='bmi',
        ),
        migrations.RemoveField(
            model_name='diabetesinput',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='diabetesinput',
            name='Diabetes_Pedigree',
        ),
        migrations.RemoveField(
            model_name='diabetesinput',
            name='Insulin',
        ),
        migrations.RemoveField(
            model_name='diabetesinput',
            name='Skin_Thickness',
        ),
        migrations.RemoveField(
            model_name='diabetesinput',
            name='pregancies',
        ),
    ]
