# Generated by Django 4.2.7 on 2024-03-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes_predictor', '0004_diabetesinput_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetesinput',
            name='Age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='DiabetesPedigree',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='Prediction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='blood_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='insulin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='pregnancies',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetesinput',
            name='skinthickness',
            field=models.FloatField(),
        ),
    ]
